baseURL = 'https://sarrolen.neocities.org/'
languageCode = 'en-us'
title = 'Adventures In Sarrolen'
theme = 'm10c'
pagintate = 10

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = '1'
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    weight = '2'
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    weight = '3'

[params]
  author = 'Tommie Matherne'
  description = 'Sarrolen. A land tranquil and untouched for fifty years. But it is breaking...'
  menu_item_separator = ' - '
  cover = 'static/cover.jpg'
